### ISSUE TITLE
Workaround for needing containium/clojure for AOT

### ISSUE THREAD

**Issue by aroemers** [touch/clojure#2]
In other words, is there another solution for:
https://github.com/containium/clojure/commit/ef5c2e31adf44a5c3527b509e340845b5c05650b

**Comment by vizanto** [comment]
The problem is lazy loading happening in another thread that doesn't have the Thread context classloader set.

Maybe we can add some trickerty to `RT.baseLoader()`, but how to figure out which classloader originally compiled the proxy?
